import os

root = 'fibonacci'
test_root = root + '_test'

test_program = Command(test_root, [s + '.chpl' for s in (root, test_root)], 'chpl -o $TARGET $SOURCES', ENV=os.environ)

Default(Command('test', test_program, './$SOURCE'))
Clean('.', Glob('*~'))
