import pathlib
import os

root = 'Fibonacci'
test_root = root + '_Test'

test_program = Command(
    test_root,
    [str(pathlib.Path('src') / (root + '.chpl')), str(pathlib.Path('test') / (test_root + '.chpl'))],
    f'chpl -o $TARGET --main-module {test_root} $SOURCES',
    ENV=os.environ,
)

Default(Command('test', test_program, './$SOURCE'))

Clean('.', Glob('*~') + Glob('*/*~'))
