import os

environment = Environment(
    tools=['g++', 'gnulink'],
    CXXFLAGS=['-std=c++14', '-O3', '-W', '-Wall', '-Wundef', '-Wcast-align', '-Wno-unused-parameter', '-Wredundant-decls'],
    CPPPATH=[os.environ['HOME'] + '/include'],
   )

environment.Program('fibonacci_test', ['fibonacci_test.cpp', 'fibonacci.cpp'])
