import os

environment = Environment(
    tools=['g++', 'gnulink'],
    CXXFLAGS=['-std=c++17', '-O3', '-W', '-Wall', '-Wundef', '-Wcast-align', '-Wno-unused-parameter', '-Wredundant-decls'],
    CPPPATH=[os.environ['HOME'] + '/include'],
   )

test_program = environment.Program('fibonacci_test', ['fibonacci_test.cpp', 'fibonacci.cpp'])

Default(test_program)
Command('test', test_program, './$SOURCE')
Clean('.', Glob('*~'))
